#!/usr/bin/env bash
# This script transfers a file from the client to a server using scp.

# Check if the correct number of parameters is provided.
if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables for clarity.
file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

# Disable strict host key checking when using scp.
scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username@$server_ip":~/ && \
echo "File transferred successfully to $username@$server_ip:~/"
