#!/usr/bin/env bash
# This script configures Nginx to add a custom X-Served-By header in HTTP responses

# Update the package list
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Configure custom header in Nginx
echo 'add_header X-Served-By $hostname;' | sudo tee -a /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
