#!/usr/bin/env bash
# This script installs and configures HAProxy on an Ubuntu machine

# Update the package list
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Configure HAProxy
echo "
frontend http-in
  bind *:80
  default_backend web-servers

backend web-servers
  balance roundrobin
  server web-01 [STUDENT_ID]-web-01:80 check
  server web-02 [STUDENT_ID]-web-02:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable HAProxy init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy

# Restart HAProxy to apply changes
sudo service haproxy restart
