#!/bin/bash

# Configure ufw to block all incoming traffic except for specific ports
sudo ufw default deny incoming  # Block all incoming traffic by default
sudo ufw allow 22/tcp           # Allow SSH (port 22) traffic
sudo ufw allow 80/tcp           # Allow HTTP (port 80) traffic
sudo ufw allow 443/tcp          # Allow HTTPS SSL (port 443) traffic
sudo ufw enable                 # Enable the firewall with the new rules
